"""Generate fake run directories.

The GUI is a watcher over a run directory, so it can be built and exercised
before any docking engine exists -- provided something produces run directories
that look real. That is this module's only job.

It is also how the GUI gets tested against conditions that are tedious to
provoke with a real engine: a run that fails a fraction of its ligands, a run
killed halfway through, a run large enough that a non-virtualised results table
would fall over.

Not a testing-only detail: ``drydock dev synthesize-run --live`` is the
supported way to watch the GUI update in real time without waiting on a screen.
"""

from __future__ import annotations

import random
import time
from pathlib import Path
from typing import Any

from drydock.core.rundir import LigandResult, PoseMode, RunDir, RunStatus

# Roughly the shape of a real Vina run against a well-formed pocket: most
# compounds land in a broad band around -6.5, with a thin tail of good binders.
_AFFINITY_MEAN = -6.5
_AFFINITY_SD = 1.4


def _synth_modes(rng: random.Random, n_modes: int) -> tuple[PoseMode, ...]:
    """Build a plausible mode table: monotonically worsening, RMSD growing."""
    best = rng.gauss(_AFFINITY_MEAN, _AFFINITY_SD)
    modes = []
    affinity = best
    for i in range(1, n_modes + 1):
        if i == 1:
            lb = ub = 0.0
        else:
            # Vina's reported RMSDs are relative to mode 1, so they drift up.
            lb = round(abs(rng.gauss(2.0, 1.0)), 3)
            ub = round(lb + abs(rng.gauss(1.5, 1.0)), 3)
            affinity += abs(rng.gauss(0.15, 0.12))
        modes.append(PoseMode(mode=i, affinity=round(affinity, 1), rmsd_lb=lb, rmsd_ub=ub))
    return tuple(modes)


def synthesize_run(
    path: str | Path,
    n_ligands: int = 500,
    *,
    seed: int = 0,
    failure_rate: float = 0.02,
    n_modes: int = 9,
    engine: str = "vina",
    live: bool = False,
    delay_s: float = 0.05,
    id_prefix: str = "LIG",
    complete: bool = True,
) -> RunDir:
    """Write a synthetic run directory.

    Args:
        path: Directory to create.
        n_ligands: Number of ligands the run covers.
        seed: Seeds the generator, so a given call reproduces byte-for-byte.
        failure_rate: Fraction recorded as failed, to exercise error paths.
        n_modes: Binding modes per successful ligand.
        engine: Engine name recorded in status and provenance.
        live: Sleep ``delay_s`` between records, so a watcher sees it progress.
        delay_s: Pause between records when ``live``.
        id_prefix: Ligand ID prefix.
        complete: If False, stop at ~60% and leave the run marked ``running`` --
            which is what a killed run looks like on disk, and the state a
            resume has to cope with.

    Returns:
        The populated :class:`RunDir`.
    """
    rng = random.Random(seed)
    run = RunDir(path).create()

    run.config_file.write_text(
        "# Synthetic run generated by drydock.core.synthetic -- not a real screen.\n"
        f'engine = "{engine}"\n'
        f"seed = {seed}\n"
        f'receptor = "synthetic_receptor.pdbqt"\n'
        f'ligands = "synthetic_ligands/"\n\n'
        "[box]\ncenter = [70.3, 19.0, 54.2]\nsize = [24.0, 24.0, 26.0]\n",
        encoding="utf-8",
    )

    provenance: dict[str, Any] = {
        "synthetic": True,
        "drydock_version": "0.1.0",
        "engine": engine,
        "scoring": engine,
        "global_seed": seed,
        "n_ligands": n_ligands,
        "receptor_sha256": "0" * 64,
        "library_sha256": "0" * 64,
        "created_at": time.time(),
    }
    run.write_provenance(provenance)

    n_written = n_ligands if complete else max(1, int(n_ligands * 0.6))
    status = RunStatus(
        state="running",
        total=n_ligands,
        started_at=time.time(),
        engine=engine,
    )
    run.write_status(status)

    for i in range(n_written):
        ligand_id = f"{id_prefix}{i + 1}"
        ligand_seed = rng.randint(0, 2**31 - 1)
        failed = rng.random() < failure_rate
        if failed:
            result = LigandResult(
                ligand_id=ligand_id,
                status="failed",
                seed=ligand_seed,
                elapsed_s=round(rng.uniform(0.1, 0.5), 3),
                error="synthetic failure: engine returned no poses",
            )
            status.failed += 1
        else:
            result = LigandResult(
                ligand_id=ligand_id,
                status="ok",
                seed=ligand_seed,
                elapsed_s=round(rng.uniform(1.5, 25.0), 3),
                modes=_synth_modes(rng, n_modes),
            )
            status.completed += 1
        run.append(result)

        # Refresh the cached status periodically rather than per ligand: a
        # watcher polls at human timescales, and rewriting it 47,000 times
        # would cost more than it saves.
        if live or (i % 25 == 0):
            run.write_status(status)
        if live:
            time.sleep(delay_s)

    if complete:
        status.state = "finished"
        status.finished_at = time.time()
    run.write_status(status)
    return run
